services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket
      POSTGRES_DB: ticketbooking
    ports:
      - "5432:5432"
